{
  imports = [
    ./aider.nix
    ./ai-packages.nix
    ./ai-services.nix
    ./brain-service.nix
    ./context-forge.nix
    ./everos.nix
    ./langgraph.nix
    ./llm-agents.nix
    ./llm-agents-catalog.nix
    ./memory-vault.nix
    ./memory-governance.nix
    ./mission-control.nix
    ./opencompany.nix
    ./paperclip.nix
    ./polyfloor.nix
    ./polyfloor-secrets.nix
  ];
}
