[audio]
enable_overdrive = true
enable_sounds = true
notification_sound = "/home/t0psh31f/Clan/NFP/layers/00-cyberia/02-assets/SFX/Navi(Extra)/446.wav"
sound_volume = 0.5
volume_change_sound = "/home/t0psh31f/Clan/NFP/layers/00-cyberia/02-assets/SFX/volume-feedback.wav"

[backdrop]
blur_intensity = 0.40000000596046448
enabled = true
tint_intensity = 0.60000002384185791

[bar]
order = [ "default" ]

    [bar.default]
    auto_hide = false
    background_opacity = 0.32999998331069946
    border = "secondary"
    border_width = 0.0
    capsule = true
    capsule_border = "primary"
    capsule_fill = "primary"
    capsule_group = []
    capsule_opacity = 0.23999999463558197
    capsule_padding = 6.0
    capsule_thickness = 0.75999999046325684
    center = [ "wallpaper", "media", "clipboard", "cat" ]
    color = "primary"
    contact_shadow = true
    enabled = true
    end = [
        "notifications",
        "tray",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "clock",
        "session",
        "control-center"
    ]
    font_weight = 500
    icon_color = "secondary"
    layer = "top"
    margin_edge = 0
    margin_ends = 30
    margin_opposite_edge = 0
    padding = 13
    panel_overlap = -2
    position = "top"
    radius = 12
    radius_bottom_left = 20
    radius_bottom_right = 20
    radius_top_left = -68
    radius_top_right = -68
    reserve_space = true
    scale = 1.1499999761581421
    shadow = false
    show_on_workspace_switch = true
    start = [ "launcher", "workspaces" ]
    thickness = 44
    widget_spacing = 3

        [bar.default.dead_zone]
        command = ""
        middle_command = ""
        right_command = ""
        scroll_down_command = ""
        scroll_up_command = ""

[battery]
warning_threshold = 10

    [battery.device."/org/freedesktop/UPower/devices/mouse_dev_4E_B6_4B_9A_28_22"]
    warning_threshold = 10

[brightness]
enable_ddcutil = false
ignore_mmids = []
minimum_brightness = 0.0
sync_all_monitors = true

[calendar]
enabled = true
refresh_minutes = 240

    [calendar.account.personal_google]
    calendars = []
    color = "primary"
    name = "WE77"
    provider = ""
    server_url = ""
    type = "google"
    username = ""

    [calendar.account.secondary_google]
    calendars = []
    color = "secondary"
    name = "LL"
    provider = ""
    server_url = ""
    type = "google"
    username = ""

[control_center]
hidden_tabs = []
sidebar = "full"
sidebar_section = "full"
width = 920

    [control_center.calendar]
    show_events_card = true

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

    [[control_center.shortcuts]]
    type = "wallpaper"

    [[control_center.shortcuts]]
    type = "power_profile"

[desktop_widgets]
enabled = true
schema_version = 2

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

[dock]
active_monitor_only = false
active_opacity = 1.0
active_scale = 1.0
auto_hide = false
background_opacity = 0.81000000238418579
cross_axis_padding = 8
enabled = false
icon_size = 48
inactive_opacity = 0.85000002384185791
inactive_scale = 0.85000002384185791
item_spacing = 6
launcher_custom_image = "/home/t0psh31f/.icons/Anime/1P/one-piece-jolly-roger-icons-by-crountch/png/256x256/Zoro.png"
launcher_custom_image_colorize = false
launcher_icon = "yin-yang-filled"
launcher_position = "start"
magnification = true
magnification_scale = 1.3500000238418579
main_axis_padding = 16
margin_edge = 2
margin_ends = 0
monitors = [ "eDP-1", "DP-2" ]
pinned = [ "Brave" ]
position = "bottom"
radius = 23
radius_bottom_left = 23
radius_bottom_right = 23
radius_top_left = 23
radius_top_right = 23
reserve_space = false
shadow = true
show_dots = true
show_instance_count = true
show_running = true

[hooks]
battery_charging = []
battery_discharging = []
battery_percentage_changed = []
battery_plugged = []
bluetooth_disabled = []
bluetooth_enabled = []
colors_changed = [ "noctalia-hypr-reload" ]
logging_out = []
power_profile_changed = []
rebooting = []
session_locked = []
session_unlocked = []
shutting_down = []
started = []
theme_mode_changed = []
wallpaper_changed = [ "noctalia-hypr-reload" ]
wifi_disabled = []
wifi_enabled = []

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 2.0

    [idle.behavior.lock]
    action = "lock"
    command = ""
    enabled = false
    resume_command = ""
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    command = ""
    enabled = false
    resume_command = ""
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    command = ""
    enabled = true
    resume_command = ""
    timeout = 660.0

[keybinds]
cancel = [ "Escape" ]
down = [ "Down", "Alt+k" ]
left = [ "Left", "Alt+h" ]
right = [ "Right", "Alt+l" ]
tab_next = [ "Tab" ]
tab_previous = [ "Shift+ISO_Left_Tab" ]
up = [ "Up", "Alt+j" ]
validate = [ "Return", "KP_Enter", "space" ]

[location]
address = "Los Angeles, CA"
auto_locate = true
sunrise = ""
sunset = ""

[lockscreen]
allow_empty_password = false
blur_intensity = 0.5
blurred_desktop = false
enabled = true
fingerprint = true
monitors = []
tint_intensity = 0.30000001192092896
wallpaper = "/home/t0psh31f/.background/4k Background/blue-one-piece-zoro-4k-82429jb4apj2vznp.jpg"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    enabled = true
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 800.0
    cy = 881.0
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true
force = false
temperature_day = 6500
temperature_night = 4000

[notification]
background_opacity = 0.93999999761581421
collapse_on_dismiss = true
enable_daemon = true
layer = "overlay"
monitors = []
offset_x = 20
offset_y = 8
position = "top_right"
scale = 1.0
show_actions = true
show_app_name = true

[osd]
background_opacity = 0.97000002861022949
monitors = []
offset_x = 20
offset_y = 8
orientation = "horizontal"
position = "bottom_center"
position_vertical = "center_right"
scale = 1.0

    [osd.kinds]
    bluetooth = true
    brightness = true
    caffeine = true
    dnd = true
    keyboard_layout = true
    lock_keys = true
    media = true
    nightlight = true
    power_profile = true
    privacy = true
    volume = true
    volume_input = true
    volume_output = true
    wifi = true

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder", "noctalia/notes", "noctalia/wallhaven" ]

    [[plugins.source]]
    auto_update = true
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    auto_update = true
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
app_icon_colorize = false
avatar_path = "/home/t0psh31f/Clan/NFP/layers/00-cyberia/02-assets/png-ico/Zoro.png"
clipboard_auto_paste = "auto"
clipboard_confirm_clear_history = true
clipboard_enabled = true
clipboard_history_max_entries = 100
clipboard_image_action_command = ""
corner_radius_scale = 1.0
date_format = ""
disable_mipmaps = false
external_ip_enabled = true
font_family = "JetBrainsMono NF Medium"
launch_apps_as_systemd_services = true
launch_apps_custom_command = ""
middle_click_opens_widget_settings = true
niri_overview_type_to_launch_enabled = false
offline_mode = false
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
setup_wizard_enabled = true
shared_gl_context = true
show_location = true
telemetry_enabled = true
time_format = "{:%H:%M:%S}"
ui_scale = 1.1000000238418579

    [shell.animation]
    enabled = true
    speed = 0.75

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    app_grid = true
    categories = true
    compact = true
    session_search = true
    show_icons = true
    sort_by_usage = true

        [shell.launcher.dmenu]

    [shell.mpris]
    blacklist = []

    [shell.panel]
    borders = true
    clipboard_placement = "floating"
    clipboard_position = "center"
    control_center_placement = "attached"
    control_center_position = "auto"
    floating_offset = 8
    launcher_placement = "attached"
    launcher_position = "center"
    open_near_click_clipboard = true
    open_near_click_control_center = false
    open_near_click_launcher = false
    open_near_click_session = false
    open_near_click_wallpaper = false
    polkit_placement = "floating"
    polkit_position = "center"
    session_placement = "attached"
    session_position = "auto"
    shadow = true
    transparency_mode = "glass"
    wallpaper_placement = "attached"
    wallpaper_position = "auto"

    [shell.privacy]
    cam_filter_regex = ""
    mic_filter_regex = ""
    screen_filter_regex = ""

    [shell.screen_corners]
    enabled = true
    size = 32

    [shell.screenshot]
    confirm_region = true
    copy_to_clipboard = true
    directory = ""
    filename_pattern = ""
    freeze_screen = true
    pipe_command = ""
    pipe_to_command = false
    save_to_file = true

    [shell.session.power]

    [[shell.session.actions]]
    action = "lock"
    command = ""
    countdown_seconds = 0.0
    enabled = true
    glyph = ""
    label = ""
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = ""
    countdown_seconds = 0.0
    enabled = true
    glyph = ""
    label = ""
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    command = ""
    countdown_seconds = 0.0
    enabled = true
    glyph = ""
    label = ""
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = ""
    countdown_seconds = 0.0
    enabled = true
    glyph = ""
    label = ""
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = ""
    countdown_seconds = 0.0
    enabled = true
    glyph = ""
    label = ""
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.55000001192092896
    direction = "down"

[system.monitor]
cpu_poll_seconds = 2.0
cpu_temp_activity_threshold = 60.0
cpu_temp_critical_threshold = 85.0
cpu_temp_sensor_path = ""
cpu_usage_activity_threshold = 50.0
cpu_usage_critical_threshold = 90.0
disk_pct_activity_threshold = 80.0
disk_pct_critical_threshold = 95.0
disk_poll_seconds = 10.0
enabled = true
gpu_poll_seconds = 60.0
gpu_temp_activity_threshold = 60.0
gpu_temp_critical_threshold = 85.0
gpu_usage_activity_threshold = 50.0
gpu_usage_critical_threshold = 95.0
gpu_vram_activity_threshold = 50.0
gpu_vram_critical_threshold = 90.0
memory_poll_seconds = 2.0
net_rx_activity_threshold = 1.0
net_rx_critical_threshold = 50.0
net_tx_activity_threshold = 1.0
net_tx_critical_threshold = 50.0
network_poll_seconds = 3.0
ram_pct_activity_threshold = 60.0
ram_pct_critical_threshold = 90.0
swap_pct_activity_threshold = 20.0
swap_pct_critical_threshold = 80.0

[theme]
builtin = "Noctalia"
community_palette = "Creamy Forest"
custom_palette = ""
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [
        "btop",
        "cava",
        "gtk3",
        "gtk4",
        "ghostty",
        "helix",
        "hyprland",
        "kcolorscheme",
        "kitty",
        "qt",
        "starship",
        "wezterm"
    ]
    community_ids = [
        "pi-agent",
        "spicetify",
        "pywalfox",
        "neovim",
        "obsidian",
        "vscode",
        "zed",
        "rofi",
        "vicinae",
        "discord",
        "papirus-icons",
        "telegram",
        "yazi",
        "zathura",
        "snappy-switcher",
        "hyprtoolkit"
    ]
    enable_builtin_templates = true
    enable_community_templates = true

[wallpaper]
directory = "/home/t0psh31f/.background/4k Background"
directory_dark = "/home/t0psh31f/.background/4k Background"
directory_light = ""
edge_smoothness = 0.30000001192092896
enabled = true
fill_color = "surface"
fill_mode = "crop"
per_monitor_directories = false
transition = [ "honeycomb" ]
transition_duration = 17600.0
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    interval_seconds = 900
    order = "random"
    recursive = true

    [wallpaper.monitor.DP-1]
    directory = "$HOME/.background/4k Background"
    match = "DP-1"

    [wallpaper.monitor.HDMI-A-1]
    directory = "$HOME/.background/4k Background"
    match = "HDMI-A-1"

    [wallpaper.monitor.eDP-1]
    directory = "$HOME/.background/4k Background"
    match = "eDP-1"

[weather]
effects = true
enabled = true
refresh_minutes = 30
unit = "imperial"

[widget.active_window]
icon_size = 14.0
max_length = 260.0
min_length = 80.0
title_scroll = "none"
type = "active_window"

[widget.battery]
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "on_primary"
capsule_opacity = 0.92000000000000004
display_mode = "graphic"
hide_when_full = true
scale = 1.1000000000000001
type = "battery"

[widget.bluetooth]
enabled = false
type = "bluetooth"

[widget.brightness]
enabled = false
show_label = false
type = "brightness"

[widget.cat]
audio_spectrum = true
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "secondary"
capsule_opacity = 0.92000000000000004
color = "primary"
icon_color = "on_primary"
rave_mode = true
scale = 1.4000000000000001
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clipboard]
capsule = false
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "on_primary"
capsule_opacity = 0.91000000000000003
custom_image = "/home/t0psh31f/Pictures/Prompt/27.gif"
scale = 2.5
type = "clipboard"

[widget.clock]
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "on_primary"
capsule_opacity = 0.90000000000000002
format = "{:%H:%M:%S}"
scale = 1.1000000000000001
type = "clock"

[widget.control-center]
capsule = false
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "secondary"
capsule_opacity = 0.91000000000000003
custom_image = "/home/t0psh31f/.icons/Anime/1P/one-piece-jolly-roger-icons-by-crountch/png/256x256/Luffys flag.png"
scale = 2.0500000000000003
type = "control-center"

[widget.cpu]
stat = "cpu_usage"
type = "sysmon"

[widget.date]
format = "{:%a %d %b}"
type = "clock"

[widget.input_volume]
device = "input"
type = "volume"

[widget.keyboard_layout]
cycle_command = ""
hide_when_single_layout = false
type = "keyboard_layout"

[widget.launcher]
capsule = false
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "primary"
capsule_opacity = 0.47000000000000003
custom_image = "/home/t0psh31f/Clan/NFP/layers/00-cyberia/02-assets/png-ico/Zoro.png"
glyph = "brand-xbox"
scale = 2.5
type = "launcher"

[widget.lock_keys]
display = "short"
hide_when_off = false
show_caps_lock = true
show_num_lock = true
show_scroll_lock = false
type = "lock_keys"

[widget.media]
art_size = 16.0
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "secondary"
capsule_opacity = 0.93000000000000005
color = "primary"
hide_when_no_media = true
icon_color = "primary"
max_length = 235
min_length = 116
title_scroll = "always"
type = "media"

[widget.network]
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "on_primary"
capsule_opacity = 0.90000000000000002
color = "primary"
enabled = true
icon_color = "primary"
show_label = false
type = "network"

[widget.network_rx]
stat = "net_rx"
type = "sysmon"

[widget.network_tx]
stat = "net_tx"
type = "sysmon"

[widget.notifications]
capsule = true
hide_when_no_unread = true
type = "notifications"

[widget.output_volume]
device = "output"
type = "volume"

[widget.ram]
stat = "ram_used"
type = "sysmon"

[widget.session]
enabled = false
type = "session"

[widget.spacer]
type = "spacer"

[widget.temp]
stat = "cpu_temp"
type = "sysmon"

[widget.tray]
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "secondary"
capsule_opacity = 0.93000000000000005
color = "secondary"
drawer = true
icon_color = "secondary"
type = "tray"

[widget.volume]
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "tertiary"
capsule_opacity = 0.85999999999999999
capsule_padding = 11
scale = 1.1000000000000001
type = "volume"

[widget.wallpaper]
capsule = false
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "secondary"
capsule_opacity = 0.88
color = "primary"
custom_image = "/home/t0psh31f/Pictures/anime-fan-art-manga-date-a-live-anime-d5b9ace6fe7cde8e939c6cac9c9e142f.png"
enabled = true
icon_color = "primary"
scale = 2.3500000000000001
type = "wallpaper"

[widget.workspaces]
capsule = true
capsule_border = "primary"
capsule_fill = "on_primary"
capsule_foreground = "secondary"
capsule_opacity = 0.90000000000000002
color = "primary"
display = "name"
empty_color = "tertiary"
icon_color = "primary"
labels_only_when_occupied = true
type = "workspaces"
