# flake-parts/features/home/cli/file-managers/yazi.nix
#
# Yazi file manager configuration with extensive plugin support.
# This configures the native programs.yazi HM module (separate from yazelix's
# internal yazi config which is managed via yazelix.toml).
#
# When running yazi standalone, this config is used directly.
# When running through yazelix (yzx), yazelix generates its own yazi config
# but the plugins installed here are still available on the system.
#
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.cli-environment;
in
{
  config = lib.mkIf cfg.enable {
    programs.yazi = {
      enable = true;
      shellWrapperName = "y";
      enableZshIntegration = true;

      # ════════════════════════════════════════════════════════════════════════
      # Plugins — from nixpkgs yaziPlugins
      # ════════════════════════════════════════════════════════════════════════
      # These are installed to ~/.config/yazi/plugins/ and available in both
      # standalone yazi and yazelix-managed yazi sessions.
      #
      # Full list of available plugins in nixpkgs:
      #   bookmarks, bypass, chmod, compress, diff, drag, duckdb, dupes,
      #   full-border, git, githead, gitui, glow, gvfs, jjui, jump-to-char,
      #   lazygit, lsar, mactag, mediainfo, miller, mime-ext, mount,
      #   nav-parent-panel, no-status, nord, ouch, piper, projects,
      #   recycle-bin, relative-motions, restore, rich-preview, rsync,
      #   smart-enter, smart-filter, smart-paste, starship, sudo,
      #   time-travel, toggle-pane, vcs-files, wl-clipboard, yatline,
      #   yatline-catppuccin, yatline-githead
      plugins = with pkgs.yaziPlugins; {
        # ── File operations ──────────────────────────────────────────────
        bookmarks = bookmarks; # Quick directory bookmarks
        chmod = chmod; # Change file permissions inline
        compress = compress; # Compress files/folders
        ouch = ouch; # Archive handling via ouch
        rsync = rsync; # Rsync file transfer
        sudo = sudo; # Run operations with sudo

        # ── File browsing & navigation ───────────────────────────────────
        diff = diff; # View file diffs
        drag = drag; # Drag & drop support
        dupes = dupes; # Find duplicate files
        full-border = full-border; # Full border around Yazi panes

        # ── Git integration ──────────────────────────────────────────────
        gitui = gitui; # GitUI integration
        lazygit = lazygit; # Lazygit integration

        # ── Preview & info ───────────────────────────────────────────────
        glow = glow; # Markdown preview via glow
        mediainfo = mediainfo; # Media file information
        mime-ext = mime-ext; # File type by extension
        rich-preview = rich-preview; # Rich file previews
        piper = piper; # Pipe files through commands

        # ── System integration ───────────────────────────────────────────
        gvfs = gvfs; # GVFS virtual filesystem
        recycle-bin = recycle-bin; # Trash files instead of deleting
        vcs-files = vcs-files; # VCS-aware file listing
        wl-clipboard = wl-clipboard; # Wayland clipboard integration

        # ── Status line & UI ─────────────────────────────────────────────
        yatline = yatline; # Customizable status line
        yatline-githead = yatline-githead; # Git branch in status line
      };

      # ════════════════════════════════════════════════════════════════════════
      # Core settings
      # ════════════════════════════════════════════════════════════════════════
      settings = {
        manager = {
          show_hidden = true;
          sort_by = "natural";
          sort_dir_first = true;
        };
        opener = {
          edit = [
            {
              run = ''${pkgs.helix}/bin/hx "$@"'';
              block = true;
            }
          ];
        };
      };

      # Yazi theme is applied via theme.toml generated by matugen/Noctalia

      # ════════════════════════════════════════════════════════════════════════
      # Keymaps
      # ════════════════════════════════════════════════════════════════════════
      keymap = {
        manager.prepend_keymap = [
          {
            on = [ "e" ];
            run = "open";
            desc = "Open with Helix";
          }
          {
            on = [ "<C-s>" ];
            run = "escape";
            desc = "Exit yazi";
          }
          # ── Bookmark keybindings ─────────────────────────────────────────
          {
            on = [
              "b"
              "a"
            ];
            run = "plugin bookmarks save";
            desc = "Add bookmark";
          }
          {
            on = [
              "b"
              "g"
            ];
            run = "plugin bookmarks jump";
            desc = "Jump to bookmark";
          }
          {
            on = [
              "b"
              "d"
            ];
            run = "plugin bookmarks delete";
            desc = "Delete bookmark";
          }
          # ── Compression ─────────────────────────────────────────────────
          {
            on = [ "C" ];
            run = "plugin compress";
            desc = "Compress selected files";
          }
          # ── Diff ────────────────────────────────────────────────────────
          {
            on = [ "D" ];
            run = "plugin diff";
            desc = "Diff selected files";
          }
          # ── Chmod ───────────────────────────────────────────────────────
          {
            on = [
              "c"
              "m"
            ];
            run = "plugin chmod";
            desc = "Change file permissions";
          }
          # ── Git tools ──────────────────────────────────────────────────
          {
            on = [
              "g"
              "u"
            ];
            run = "plugin gitui";
            desc = "Open GitUI";
          }
          {
            on = [
              "g"
              "l"
            ];
            run = "plugin lazygit";
            desc = "Open Lazygit";
          }
          # ── Recycle bin ─────────────────────────────────────────────────
          {
            on = [
              "d"
              "t"
            ];
            run = "plugin recycle-bin delete";
            desc = "Move to recycle bin";
          }
          {
            on = [
              "d"
              "r"
            ];
            run = "plugin recycle-bin restore";
            desc = "Restore from recycle bin";
          }
          # ── Wayland clipboard ──────────────────────────────────────────
          {
            on = [
              "y"
              "c"
            ];
            run = "plugin wl-clipboard";
            desc = "Copy to Wayland clipboard";
          }
        ];
      };
    };
  };
}
