{
  imports = [
    ./48-utilities/accessories.nix
    ../60-gui-programs/61-browsers/brave.nix
    ../60-gui-programs/61-browsers/librewolf.nix
    ./45-file-managers/dolphin.nix
    ./45-file-managers/nemo.nix
    ./46-terminal-emulators/default.nix
    ./41-hyprland/default.nix
    ../60-gui-programs/62-media/mpv.nix
    ../60-gui-programs/62-media/vlc.nix
    ../60-gui-programs/62-media/audio.nix
    ./43-noctalia/default.nix
    ./42-niri/default.nix
    ./47-display/shikane.nix
    ./48-utilities/social.nix
    ./44-de-frameworks/vicinae.nix
  ];
}
